services:
  backend:
    image: shop_app
    container_name: shop_app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user      # ${DB_USER}
      POSTGRES_PASSWORD: psswd       # ${DB_PASSWORD}
      POSTGRES_DB: postgresDB        # ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgresDB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - './migrations/:/docker-entrypoint-initdb.d/'
    # command: ["postgres", "-c", "log_statement=all"] 
    