// Code generated by MockGen. DO NOT EDIT.
// Source: getUserInfo.go

// Package getuserinfo is a generated GoMock package.
package getuserinfo

import (
	models "avito-shop-service/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserInfoGetter is a mock of UserInfoGetter interface.
type MockUserInfoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoGetterMockRecorder
}

// MockUserInfoGetterMockRecorder is the mock recorder for MockUserInfoGetter.
type MockUserInfoGetterMockRecorder struct {
	mock *MockUserInfoGetter
}

// NewMockUserInfoGetter creates a new mock instance.
func NewMockUserInfoGetter(ctrl *gomock.Controller) *MockUserInfoGetter {
	mock := &MockUserInfoGetter{ctrl: ctrl}
	mock.recorder = &MockUserInfoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfoGetter) EXPECT() *MockUserInfoGetterMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockUserInfoGetter) GetUserInfo(arg0 context.Context, arg1 string) (models.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", arg0, arg1)
	ret0, _ := ret[0].(models.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockUserInfoGetterMockRecorder) GetUserInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockUserInfoGetter)(nil).GetUserInfo), arg0, arg1)
}
